---
name: Build server container image
on:
  pull_request:
    branches:
      - main

  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday

  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "desktop.containerfile"

  workflow_dispatch:

jobs:
  build_image:
    name: Build image
    uses: ${GITHUB_WORKSPACE}/.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        image_flavor: ["server"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
